application:
  port: 8080
  host: 0.0.0.0
  hmac_secret: "asljkdhflkjansdv892398h2uin3f9w8newf980cwne9uvnw980evcnsw908nv9u"
  tls_enabled: false
  cert_file_path: "./security/cert.pem"
  key_file_path: "./security/key.pem"
  resume_file_path: "./data/Robert_eklund_resume.pdf"
  headshot_file_path: "./data/Avatar.jpeg"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "me@roberteklund.us"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"