name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Tauri Init
        run: |
          cargo install tauri-cli
          rustup target add wasm32-unknown-unknown
          cargo install trunk
          cargo install wasm-bindgen-cli
          cargo install cargo-audit
      - name: Format
        run: cargo fmt -- --check
      - name: Build
        run: cargo tauri build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Audit
        run: cargo audit